-- GUI - 10/12/2018
-- script de creación de la bd GUIBD.
--
-- CREAR LA BD BORRANDOLA SI YA EXISTIESE
--
DROP DATABASE IF EXISTS `GUIBD`;
CREATE DATABASE `GUIBD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- SELECCIONAMOS PARA USAR
--
USE `GUIBD`;
--
-- DAMOS PERMISO USO Y BORRAMOS EL USUARIO QUE QUEREMOS CREAR POR SI EXISTE
--
GRANT USAGE ON * . * TO `GUIBD`@`localhost`;
DROP USER `GUIBD`@`localhost`;
--
-- CREAMOS EL USUARIO Y LE DAMOS PASSWORD,DAMOS PERMISO DE USO Y DAMOS PERMISOS SOBRE LA BASE DE DATOS.
--
CREATE USER IF NOT EXISTS `GUIBD`@`localhost` IDENTIFIED BY 'passGUIBD';
GRANT USAGE ON *.* TO `GUIBD`@`localhost` REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `GUIBD`.* TO `GUIBD`@`localhost` WITH GRANT OPTION;
--
-- Estructura de tabla para la tabla `datos`
--
CREATE TABLE IF NOT EXISTS `` (
`login` varchar(15) NOT NULL,
`password` varchar(128) NOT NULL,
`nombre` varchar(30) NOT NULL,
`apellidos` varchar(50) NOT NULL,
`email` varchar(60) NOT NULL,
`FechaNacimiento` date NOT NULL,
`avatar` varchar(50) NOT NULL,
`admin` enum('true','false') NOT NULL,
PRIMARY KEY (`login`),
UNIQUE KEY `email` (`email`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;